a = 10
b = 4
print(f"Addition: {a} + {b} = {a + b}")
print(f"Substraction: {a} - {b} = {a - b}")
print(f"Multiplication: {a} * {b} = {a * b}")
print(f"Division: {a} / {b} = {a / b}")
print(f"Floor Division: {a} // {b} = {a // b}")
print(f"Remainder: {a} % {b} = {a % b}")
print(f"Power: {a} ** {b} = {a ** b}")